# Generated by Django 4.2.2 on 2023-06-21 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0004_alter_question_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="quiz",
            options={"verbose_name_plural": "Quizzes"},
        ),
        migrations.AlterField(
            model_name="choice",
            name="is_correct",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="choice",
            name="text",
            field=models.TextField(max_length=1200),
        ),
        migrations.AlterField(
            model_name="question",
            name="order_number",
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(25)]),
        ),
    ]
