version: "3"

services:
  backend:
    build: ./
    container_name: quiz_container
    working_dir: /quiz
    command:
      - ./commands/start_server.sh
    ports:
      - 8010:8000
    volumes:
      - ./src:/quiz/src
      - ./commands:/quiz/commands
