version: "3"

services:
  backend:
    build: ./
    container_name: quiz_container
    working_dir: /quiz
    command:
      - ./commands/start_server_${MODE}.sh
    ports:
      - 8010:8000
    volumes:
      - ./src:/quiz/src
      - ./commands:/quiz/commands
      - static_content:/quiz/src/static_content
      - media_content:/quiz/src/media_content
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: on-failure
    env_file:
      - .env
    ports:
      - 5000:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  nginx:
    image: nginx:1.19
    volumes:
      - static_content:/quiz/src/static
      - media_content:/quiz/src/media
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    depends_on:
      - backend

volumes:
  static_content: { }
  media_content: { }
  pg_data: { }
  pgadmin_data: { }